spring.application.name=SahaYatri-Backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

twilio.account.sid=${TWILIO_ACC_SID}
twilio.auth.token=${TWILIO_ACC_TOKEN}
twilio.phone.number=${TWILIO_ACC_NUM}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}

face.api.url=${FACE_API_URL}
face.api.key=${FACE_API_KEY}
face.api.secret=${FACE_API_SECRET}

match.confidence.threshold=80.0
